### ISSUE TITLE
[Bug] Simple VoiceChat

### ISSUE THREAD

**Issue by UTrosh** [FoxyCraftNetwork/Forge-Client-Reset-Packet#2]
![image](https://github.com/wolflord212312/Forge-Client-Reset-Packet/assets/73399986/a22dd7b5-f278-4614-852e-c7014f2e50df)
Here is client logs :
[02sept.2023 12:05:20.444] [Render thread/INFO] [net.minecraft.client.gui.components.ChatComponent/]: [System] [CHAT] Sending you to survie now..
[02sept.2023 12:05:20.494] [Netty Client IO #4/INFO] [gg.chaldea.client.reset.packet.ClientReset/RESETPACKET]: Received reset packet from server.
[02sept.2023 12:05:20.496] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
[02sept.2023 12:05:20.497] [Render thread/INFO] [mezz.jei.forge.startup.StartEventObserver/]: JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
[02sept.2023 12:05:20.497] [Render thread/INFO] [mezz.jei.library.startup.JeiStarter/]: Stopping JEI
[02sept.2023 12:05:20.497] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable...
[02sept.2023 12:05:20.498] [Render thread/INFO] [mezz.jei.forge.plugins.forge.ForgeGuiPlugin/]: Stopping JEI GUI
[02sept.2023 12:05:20.500] [Render thread/INFO] [mezz.jei.library.load.PluginCaller/]: Sending Runtime Unavailable took 3.385 ms
[02sept.2023 12:05:20.504] [Render thread/INFO] [voicechat/]: [voicechat] Clearing audio channels
[02sept.2023 12:05:21.501] [Render thread/INFO] [ChunkBuilder/]: Stopping worker threads
[02sept.2023 12:05:21.502] [Netty Client IO #4/INFO] [gg.chaldea.client.reset.packet.ClientReset/RESETPACKET]: Reset complete.

And no error in server, just disconnected

**Comment by wolflord212312** [comment]
This can be caused by alot of things mod mismatches bad mod devs making there mod incompatible with resetting,

What version of velocity what version of ambassador, what MC version

What is the mod list and other things

**Comment by wolflord212312** [comment]
as this is the one and only issue with this since i took over working on it.

**Comment by wolflord212312** [comment]
And if your velocity network is setup properly then have you attempted connecting without forge reset client as ambassador allows for this does it give you a error there?

**Comment by trilliam25** [comment]
I'm getting the exact same issue: "Can't serialize unregistered packet"
forge 1.19.2-43.2.2
velocity-3.2.0-SNAPSHOT-260.jar
Ambassador-Velocity-1.4.1-all.jar
proxy-compatible-forge-1.19.2-1.1.4.jar
ForgeClientResetPacket-0.2.2.jar

Modlist:
- AppleSkin
- Architectury API (Fabric/Forge)
- Better Block Sounds
- Bookshelf
- Botany Pots
- Chat Heads
- Chimes
- Cloth Config API (Fabric/Forge)
- Collective
- Controlling
- Curios API (Forge)
- Death Backup
- Decorative Blocks
- Effective (Forge)
- Enchantment Descriptions
- Epic Knights: Shields, Armor and Weapons [Fabric & Forge]
- FerriteCore (Forge)
- Forward- Forge-Client-Reset-Packet
- Friends&Foes (Forge) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Illusioner, Rascal, and Tuff Golem)
- Game Menu Mod Option [Forge]
- Game Menu Remove GFARB
- GeckoLib
- Handcrafted
- Healing Campfire
- Jade 🔍
- Just Enough Items (JEI)
- Magnesium/Rubidium Dynamic Lights
- Magnesium/Rubidium Extras
- Map Atlases [Forge]
- Mouse Tweaks
- Mythic Mounts (Forge)
- Naturalist
- PackMenu
- Patchouli
- Placebo
- playerAnimator
- Puzzles Lib [Forge & Fabric]
- Resourceful Lib
- RightClickHarvest
- Rubidium
- Simple Voice Chat
- Small Ships [Fabric & Forge]
- Sophisticated Backpacks
- Sophisticated Core
- Sound Physics Remastered
- TexTrue's Rubidium Options
- Villager Recruits
- Visual Workbench [Forge & Fabric]


Client log 
`12:58:59.228
gg.chaldea.client.reset.packet.ClientReset
Netty Client IO #3
Received reset packet from server.
12:58:59.235
mezz.jei.forge.startup.StartEventObserver
Render thread
JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut
12:58:59.235
mezz.jei.forge.startup.StartEventObserver
Render thread
JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED
12:58:59.235
mezz.jei.library.startup.JeiStarter
Render thread
Stopping JEI
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:minecraft ...
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:minecraft took 13.20 μs
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:gui ...
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:gui took 2.600 μs
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:debug ...
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:debug took 1.700 μs
12:58:59.235
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:forge_gui ...
12:58:59.235
mezz.jei.forge.plugins.forge.ForgeGuiPlugin
Render thread
Stopping JEI GUI
12:58:59.237
mezz.jei.core.config.file.FileWatcherThread
JEI GUI Config file watcher
FileWatcher was interrupted, stopping.
12:58:59.237
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:forge_gui took 2.239 ms
12:58:59.237
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: visualworkbench:crafting ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: visualworkbench:crafting took 2.500 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: sophisticatedcore:default ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: sophisticatedcore:default took 1.600 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: decorative_blocks:main ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: decorative_blocks:main took 2.100 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: botanypots:jei_support ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: botanypots:jei_support took 1.300 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: sophisticatedbackpacks:default ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: sophisticatedbackpacks:default took 1.300 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jade:main ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jade:main took 1.600 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: curios:curios ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: curios:curios took 1.300 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: patchouli:patchouli ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: patchouli:patchouli took 1.800 μs
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:internal ...
12:58:59.238
mezz.jei.library.load.PluginCaller
Render thread
Sending Runtime Unavailable: jei:internal took 1.300 μs
12:58:59.238
mezz.jei.core.config.file.FileWatcherThread
JEI Library Config file watcher
FileWatcher was interrupted, stopping.
12:58:59.244
voicechat
Render thread
[voicechat] Clearing audio channels
12:58:59.246
voicechat
Render thread
[voicechat] Stopping microphone thread
12:58:59.276
voicechat
Render thread
[voicechat] Disconnecting voicechat
12:58:59.277
Sound Physics - Debug
Render thread
Clearing unused audio channels
12:58:59.703
ChunkBuilder
Render thread
Stopping worker threads
12:58:59.705
gg.chaldea.client.reset.packet.ClientReset
Netty Client IO #3
Reset complete.`

Server log:
`[17:59:01] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@2d5beb22[id=71341576-4ea2-4e00-b284-1f9acc7df12f,name=Trilliam25,properties={textures=[com.mojang.authlib.properties.Property@285cb0b4]},legacy=false] (/********) lost connection: Disconnected`

Velocity log:
`[17:59:00 INFO]: [connected player] Trilliam25 (/********) -> executed command /server event
[17:59:00 INFO]: [server connection] Trilliam25 -> Event has connected
[17:59:00 INFO]: [server connection] Trilliam25 -> Hub has disconnected
[17:59:00 INFO]: [connected player] Trilliam25 (/********) has disconnected
[17:59:00 INFO]: [server connection] Trilliam25 -> Event has disconnected`

**Comment by wolflord212312** [comment]
> I'm getting the exact same issue: "Can't serialize unregistered packet" forge 1.19.2-43.2.2 velocity-3.2.0-SNAPSHOT-260.jar Ambassador-Velocity-1.4.1-all.jar proxy-compatible-forge-1.19.2-1.1.4.jar ForgeClientResetPacket-0.2.2.jar
> 
> Modlist:
> 
> * AppleSkin
> * Architectury API (Fabric/Forge)
> * Better Block Sounds
> * Bookshelf
> * Botany Pots
> * Chat Heads
> * Chimes
> * Cloth Config API (Fabric/Forge)
> * Collective
> * Controlling
> * Curios API (Forge)
> * Death Backup
> * Decorative Blocks
> * Effective (Forge)
> * Enchantment Descriptions
> * Epic Knights: Shields, Armor and Weapons [Fabric & Forge]
> * FerriteCore (Forge)
> * Forward- Forge-Client-Reset-Packet
> * Friends&Foes (Forge) (Copper Golem, Glare, Moobloom, Iceologer, Barnacle, Wildfire, Illusioner, Rascal, and Tuff Golem)
> * Game Menu Mod Option [Forge]
> * Game Menu Remove GFARB
> * GeckoLib
> * Handcrafted
> * Healing Campfire
> * Jade 🔍
> * Just Enough Items (JEI)
> * Magnesium/Rubidium Dynamic Lights
> * Magnesium/Rubidium Extras
> * Map Atlases [Forge]
> * Mouse Tweaks
> * Mythic Mounts (Forge)
> * Naturalist
> * PackMenu
> * Patchouli
> * Placebo
> * playerAnimator
> * Puzzles Lib [Forge & Fabric]
> * Resourceful Lib
> * RightClickHarvest
> * Rubidium
> * Simple Voice Chat
> * Small Ships [Fabric & Forge]
> * Sophisticated Backpacks
> * Sophisticated Core
> * Sound Physics Remastered
> * TexTrue's Rubidium Options
> * Villager Recruits
> * Visual Workbench [Forge & Fabric]
> 
> Client log `12:58:59.228 gg.chaldea.client.reset.packet.ClientReset Netty Client IO #3 Received reset packet from server. 12:58:59.235 mezz.jei.forge.startup.StartEventObserver Render thread JEI StartEventObserver received class net.minecraftforge.client.event.ClientPlayerNetworkEvent$LoggingOut 12:58:59.235 mezz.jei.forge.startup.StartEventObserver Render thread JEI StartEventObserver transitioning state from JEI_STARTED to DISABLED 12:58:59.235 mezz.jei.library.startup.JeiStarter Render thread Stopping JEI 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:minecraft ... 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:minecraft took 13.20 μs 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:gui ... 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:gui took 2.600 μs 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:debug ... 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:debug took 1.700 μs 12:58:59.235 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:forge_gui ... 12:58:59.235 mezz.jei.forge.plugins.forge.ForgeGuiPlugin Render thread Stopping JEI GUI 12:58:59.237 mezz.jei.core.config.file.FileWatcherThread JEI GUI Config file watcher FileWatcher was interrupted, stopping. 12:58:59.237 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:forge_gui took 2.239 ms 12:58:59.237 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: visualworkbench:crafting ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: visualworkbench:crafting took 2.500 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: sophisticatedcore:default ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: sophisticatedcore:default took 1.600 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: decorative_blocks:main ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: decorative_blocks:main took 2.100 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: botanypots:jei_support ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: botanypots:jei_support took 1.300 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: sophisticatedbackpacks:default ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: sophisticatedbackpacks:default took 1.300 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jade:main ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jade:main took 1.600 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: curios:curios ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: curios:curios took 1.300 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: patchouli:patchouli ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: patchouli:patchouli took 1.800 μs 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:internal ... 12:58:59.238 mezz.jei.library.load.PluginCaller Render thread Sending Runtime Unavailable: jei:internal took 1.300 μs 12:58:59.238 mezz.jei.core.config.file.FileWatcherThread JEI Library Config file watcher FileWatcher was interrupted, stopping. 12:58:59.244 voicechat Render thread [voicechat] Clearing audio channels 12:58:59.246 voicechat Render thread [voicechat] Stopping microphone thread 12:58:59.276 voicechat Render thread [voicechat] Disconnecting voicechat 12:58:59.277 Sound Physics - Debug Render thread Clearing unused audio channels 12:58:59.703 ChunkBuilder Render thread Stopping worker threads 12:58:59.705 gg.chaldea.client.reset.packet.ClientReset Netty Client IO #3 Reset complete.`
> 
> Server log: `[17:59:01] [Server thread/INFO] [minecraft/ServerLoginPacketListenerImpl]: com.mojang.authlib.GameProfile@2d5beb22[id=71341576-4ea2-4e00-b284-1f9acc7df12f,name=Trilliam25,properties={textures=[com.mojang.authlib.properties.Property@285cb0b4]},legacy=false] (/********) lost connection: Disconnected`
> 
> Velocity log: `[17:59:00 INFO]: [connected player] Trilliam25 (/********) -> executed command /server event [17:59:00 INFO]: [server connection] Trilliam25 -> Event has connected [17:59:00 INFO]: [server connection] Trilliam25 -> Hub has disconnected [17:59:00 INFO]: [connected player] Trilliam25 (/********) has disconnected [17:59:00 INFO]: [server connection] Trilliam25 -> Event has disconnected`

OK have you atempted to see if it lets you switch servers without Forge Reset client?

**Comment by wolflord212312** [comment]
also just out of my head try disabling Simple Voice Chat 
and on client and server then atempt join

**Comment by wolflord212312** [comment]
Also is ambassador the only plugin you have on the velocity proxy?

**Comment by wolflord212312** [comment]
as voicechat is what you both have in common
So that is my only choice to blame right now

**Comment by wolflord212312** [comment]
So after testing found it to be simpleVC
Can you guys atempt without forge reset client does it give error or connect fine then?

**Comment by wolflord212312** [comment]
@trilliam25 @UTrosh https://github.com/henkelmax/simple-voice-chat/issues/625

PLEASE SEND FULL LOGS FROM ALL THE SERVERS HERE FEEL FREE TO CENSOR IPS AND CRAP BUT FULL LOGS.
